/-
Copyright (c) 2026 Riemann-Zeta project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riemann-Zeta project contributors
-/
import RHBridge.P2Containment
import RHBridge.P2EntryCertificate
import RHBridge.P2EntryTable
import RHBridge.P2EntryError
import RHBridge.P2PoleApprox
import RHBridge.PolyEnclosure
import RHBridge.P2RationalPolynomial
import RHBridge.P2DigammaTail
import RHBridge.P2DigammaPrefix
import RHBridge.P2TailTelescopers
import RHBridge.P2ElementaryConstants
import RHBridge.P2AlphaEnclosure
import RHBridge.P2SphericalApprox
import RHBridge.P2CosApprox
import RHBridge.P2DefectApprox
import RHBridge.P2SphericalReal
import RHBridge.P2ComponentBounds
import RHBridge.P2ScaleCenters
import RHBridge.P2PanelComposition
import RHBridge.P2CanonicalRational
import RHBridge.P2PoleScaleCenters
import RHBridge.P2PoleRationalCenter
import RHBridge.P2RoundedBoundedCertificateCheck
import RHBridge.ComplexResidue
import RHBridge.AutocorrelationPlancherelCore
import RHBridge.AutocorrelationPlancherel
import RHBridge.GeneralZetaWeilForm
import RHBridge.NestedSupport
import RHBridge.SupportDecomposition
import RHBridge.WeilCrossKernel
import RHBridge.GeometricCancellation
import RHBridge.UniformPropagationToRH
import RHBridge.GuinandWeilFormula
import RHBridge.GuinandWeilLiterature
import RHBridge.SuzukiScrewLiterature
import RHBridge.SuzukiPrimeRamp
import RHBridge.SmoothSupportPropagation
import RHBridge.SmoothCutoffLocalization
import RHBridge.SmoothCutoff
import RHBridge.SmoothCompactSupportData
import RHBridge.LogarithmicWeight
import RHBridge.ExplicitSmoothCutoff
import RHBridge.LocalizationLiterature
import RHBridge.ActivationCancellation
import RHBridge.SingleActivationHighFrequency
import RHBridge.EventCollarPropagation
import RHBridge.BoundaryCollarGeometry
import RHBridge.ScaleUniformLeakage
import RHBridge.RelativeCrossNecessity
import RHBridge.LowEnergySector
import RHBridge.LowEnergyRigidity
import RHBridge.SuzukiEulerLagrange
import RHBridge.ZeroModeConditions
import RHBridge.ContinuousDelayObstruction
import RHBridge.LocalizedFourierObstruction
import RHBridge.CanonicalZeroMode
import RHBridge.CanonicalShiftObstruction
import RHBridge.SuzukiKernelZeroReduction
import RHBridge.LogEllipticReduction
import RHBridge.ZeroSideOvercompleteness
import RHBridge.ZeroQuartetPhase
import RHBridge.CompressedKernelSynthesis
import RHBridge.SuzukiClosedDomainLiterature
import RHBridge.Stage2DefectCharacterization
import RHBridge.Stage3SupportSaturation
import RHBridge.Stage3BoundaryNoGo
import RHBridge.Stage3ArithmeticBoundaryTarget
import RHBridge.Stage3DeterminantLimit
import RHBridge.Stage3CCMDeterminant
import RHBridge.Stage3FiniteWindowParity
import RHBridge.Stage3ParityNoGo
import RHBridge.Stage4CanonicalResidual
import RHBridge.ZetaZeroCountingLiterature
import RHBridge.Stage4SamplingLiterature
import RHBridge.Stage4DominatedResidual
import RHBridge.Stage4FormDomainExtension
import RHBridge.Stage4FullDomainResidual
import RHBridge.ZetaZeroFreeRegionLiterature
import RHBridge.Stage4ProlateMellinCertificate
import RHBridge.Stage4CCMComparatorFamily
import RHBridge.Stage4MomentCorrection
import RHBridge.Stage4PoissonReduction
import RHBridge.Stage4CanonicalConstructionLiterature
import RHBridge.WeilCriterionLiterature
import RHBridge.RHBranchLedger
import RHBridge.RHZeroFrame
import RHBridge.ZeroSpacingBridge
import RHBridge.MetamathematicalLedger
import RHBridge.UniformSupportTransfer
import RHBridge.PrimeEdgePolarization
import RHBridge.GlobalMobiusCancellation
import RHBridge.RelativeIncidenceComplex
import RHBridge.BoundaryWeylReduction
import RHBridge.SemilocalPrimeWeight
import RHBridge.NormalizedLocalContraction
import RHBridge.SharpIncidenceTransport
import RHBridge.IncidenceAngleCriterion
import RHBridge.DualFrameCollarCompletion
import RHBridge.IncidenceCycleObstruction
import RHBridge.HodgeHighSector
import RHBridge.HodgeLowSector
import RHBridge.HodgeLowSectorNoGo

/-!
# Composed RH proof bridges

This package imports the independent `glide` and `weilcert` developments so
their kernel-checked theorems can be composed without duplicating either
development.  The current focus is the unrestricted `p = 2` endpoint.
-/
