import RHBridge.FourCauchyGlobalCompatibility

#print axioms RHBridge.FourCauchyGlobalCompatibility.scalarPullback_commutes
#print axioms RHBridge.FourCauchyGlobalCompatibility.reflection_conjugates_scalarPullback
#print axioms RHBridge.FourCauchyGlobalCompatibility.reflection_commutes_with_paired_pullback
#print axioms RHBridge.FourCauchyGlobalCompatibility.commutator_product
#print axioms RHBridge.FourCauchyGlobalCompatibility.projection_leakage_is_commutator
#print axioms RHBridge.FourCauchyGlobalCompatibility.compressed_inverse_equals_omitted_tail
#print axioms RHBridge.FourCauchyGlobalCompatibility.right_pole_lerch_leading_cancel
#print axioms RHBridge.FourCauchyGlobalCompatibility.left_pole_lerch_leading_cancel
#print axioms RHBridge.FourCauchyGlobalCompatibility.toeplitz_three_det_factor
#print axioms RHBridge.FourCauchyGlobalCompatibility.even_contact_old_rows_zero
#print axioms RHBridge.FourCauchyGlobalCompatibility.even_contact_exterior_zero_iff
#print axioms RHBridge.FourCauchyGlobalCompatibility.odd_contact_exterior_zero_iff
#print axioms RHBridge.FourCauchyGlobalCompatibility.even_boundary_stencil_residual
#print axioms RHBridge.FourCauchyGlobalCompatibility.charged_contact_old_block_sos
#print axioms RHBridge.FourCauchyGlobalCompatibility.rational_charged_contact_old_null
#print axioms RHBridge.FourCauchyGlobalCompatibility.rational_charged_contact_exterior_charge
#print axioms RHBridge.FourCauchyGlobalCompatibility.chebyshev_step_residual
