/-
Copyright (c) 2026 Riemann-Zeta project contributors. All rights reserved.
Authors: Riemann-Zeta project contributors
-/
import RHBridge.SupportDecomposition

/-!
# Geometric cancellation across an old/collar split

The useful quantity is not the norm of a translation (which is one), but the
norm remaining after translating and projecting across the support interface.
This file isolates that exact boundary-layer estimate from the subsequent
Cauchy--Schwarz argument.
-/

namespace RHP2Bridge.GeometricCancellation

open scoped RealInnerProductSpace

noncomputable section

/-- Symmetric cross interaction generated by a linear operator. -/
def operatorCross {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (T : E →ₗ[ℝ] E) (u v : E) : ℝ :=
  (inner ℝ u (T v) + inner ℝ v (T u)) / 2

/-- Cauchy--Schwarz after projection reduces a geometric cross estimate to
two boundary-layer leakage estimates.  This is the precise point at which a
logarithmic no-concentration lemma can enter. -/
theorem abs_operatorCross_le_of_projection_leakage
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (U : Submodule ℝ E) [U.HasOrthogonalProjection]
    (T : E →ₗ[ℝ] E) {u v : E} (hu : u ∈ U) (hv : v ∈ Uᗮ)
    {η : ℝ}
    (huLeak : ‖Uᗮ.starProjection (T u)‖ ≤ η * ‖u‖)
    (hvLeak : ‖U.starProjection (T v)‖ ≤ η * ‖v‖) :
    |operatorCross T u v| ≤ η * ‖u‖ * ‖v‖ := by
  have huv : inner ℝ u (T v) = inner ℝ u (U.starProjection (T v)) := by
    rw [← U.inner_starProjection_left_eq_right]
    rw [U.starProjection_eq_self_iff.mpr hu]
  have hvu : inner ℝ v (T u) = inner ℝ v (Uᗮ.starProjection (T u)) := by
    rw [← Uᗮ.inner_starProjection_left_eq_right]
    rw [Uᗮ.starProjection_eq_self_iff.mpr hv]
  have h1 : |inner ℝ u (T v)| ≤ η * ‖u‖ * ‖v‖ := by
    rw [huv]
    calc
      |inner ℝ u (U.starProjection (T v))| ≤
          ‖u‖ * ‖U.starProjection (T v)‖ := abs_real_inner_le_norm _ _
      _ ≤ ‖u‖ * (η * ‖v‖) :=
        mul_le_mul_of_nonneg_left hvLeak (norm_nonneg u)
      _ = η * ‖u‖ * ‖v‖ := by ring
  have h2 : |inner ℝ v (T u)| ≤ η * ‖u‖ * ‖v‖ := by
    rw [hvu]
    calc
      |inner ℝ v (Uᗮ.starProjection (T u))| ≤
          ‖v‖ * ‖Uᗮ.starProjection (T u)‖ := abs_real_inner_le_norm _ _
      _ ≤ ‖v‖ * (η * ‖u‖) :=
        mul_le_mul_of_nonneg_left huLeak (norm_nonneg v)
      _ = η * ‖u‖ * ‖v‖ := by ring
  unfold operatorCross
  rw [abs_div]
  have hden : |(2 : ℝ)| = 2 := by norm_num
  rw [hden]
  calc
    |inner ℝ u (T v) + inner ℝ v (T u)| / 2 ≤
        (|inner ℝ u (T v)| + |inner ℝ v (T u)|) / 2 := by
      gcongr
      exact abs_add_le _ _
    _ ≤ (2 * (η * ‖u‖ * ‖v‖)) / 2 := by
      gcongr
      linarith
    _ = η * ‖u‖ * ‖v‖ := by ring

end

end RHP2Bridge.GeometricCancellation
