import RHBridge.GuinandWeilFormula

#print axioms RHP2Bridge.GuinandWeilFormula.nontrivialZerosInDisk
#print axioms RHP2Bridge.GuinandWeilFormula.zeroMultiplicity_pos
#print axioms RHP2Bridge.GuinandWeilFormula.exists_local_zeta_factorization
#print axioms RHP2Bridge.GuinandWeilFormula.eventually_logDeriv_riemannZeta_eq_principalPart_add
#print axioms RHP2Bridge.GuinandWeilFormula.hasSum_rightContour_vonMangoldt
#print axioms RHP2Bridge.GuinandWeilFormula.logDeriv_completedRiemannZeta_eq_gammaR_add_zeta
#print axioms RHP2Bridge.GuinandWeilFormula.logDeriv_gammaR_eq_digamma
#print axioms RHP2Bridge.GuinandWeilFormula.logDeriv_completedRiemannZeta_rightContour
#print axioms RHP2Bridge.GuinandWeilFormula.rightContour_vonMangoldt_term
#print axioms RHP2Bridge.GuinandWeilFormula.logDeriv_completedRiemannZeta_one_sub
#print axioms RHP2Bridge.GuinandWeilFormula.weightedZeroExtensionFn_memLp
#print axioms RHP2Bridge.GuinandWeilFormula.fourier_weightedZeroExtensionFn_eq_bilateralLaplaceFn
#print axioms RHP2Bridge.GuinandWeilFormula.coe_fourier_weightedZeroExtensionL2_ae_eq_bilateralLaplaceFn
#print axioms RHP2Bridge.GuinandWeilFormula.weighted_crossPlancherel
#print axioms RHP2Bridge.GuinandWeilFormula.conj_bilateralLaplaceFn
#print axioms RHP2Bridge.GuinandWeilFormula.centered_verticalLine_eq_weighted_autocorrelation
#print axioms RHP2Bridge.GuinandWeilFormula.DiskHolds
#print axioms RHP2Bridge.GuinandWeilFormula.HasContourDecay
#print axioms RHP2Bridge.GuinandWeilFormula.SmoothCompactSupportData.toTestSpace
#print axioms RHP2Bridge.GuinandWeilFormula.SmoothCompactSupportData.coe_toTestSpace_ae
#print axioms RHP2Bridge.GuinandWeilFormula.hasCompactSupport_zeroExtensionFn
#print axioms RHP2Bridge.GuinandWeilFormula.smooth_weightedZeroExtensionFn
#print axioms RHP2Bridge.GuinandWeilFormula.integrable_iteratedFDeriv_weightedZeroExtensionFn
#print axioms RHP2Bridge.GuinandWeilFormula.exists_fourier_decay_constant_weighted
#print axioms RHP2Bridge.GuinandWeilFormula.holds_implies_zero_sum_real
