import RHBridge.HodgeLowSectorNoGo

/-! # Axiom audit for the low-sector DtN no-go -/

#print axioms RHP2Bridge.HodgeLowSectorNoGo.scalar_harmonic_extension_identity
#print axioms RHP2Bridge.HodgeLowSectorNoGo.negative_harmonic_extension_of_response_gt
#print axioms RHP2Bridge.HodgeLowSectorNoGo.rankOneResponse_sub_oldGap
#print axioms RHP2Bridge.HodgeLowSectorNoGo.analytic_rankOne_convolution_breaks_contraction
#print axioms RHP2Bridge.HodgeLowSectorNoGo.rational_analytic_rankOne_countermodel
#print axioms RHP2Bridge.HodgeLowSectorNoGo.twoMode_completion_identity
#print axioms RHP2Bridge.HodgeLowSectorNoGo.twoMode_determinant_pos_iff_finalPivot_pos
