import RHBridge.R188PrincipalBandSerialization

#print axioms RHBridge.R188PrincipalBandSerialization.targetExponent
#print axioms RHBridge.R188PrincipalBandSerialization.target_lt_natural
#print axioms RHBridge.R188PrincipalBandSerialization.scalarWrightTop_excess
#print axioms RHBridge.R188PrincipalBandSerialization.targetMatched_lowCofactorExponent
#print axioms RHBridge.R188PrincipalBandSerialization.targetMatched_largeNumeratorExponent
#print axioms RHBridge.R188PrincipalBandSerialization.targetMatched_quotientExponent
#print axioms RHBridge.R188PrincipalBandSerialization.targetMatched_numeratorExponent
#print axioms RHBridge.R188PrincipalBandSerialization.coreDenominator_le_scale
#print axioms RHBridge.R188PrincipalBandSerialization.nonzeroCoreMode_forces_highDenominator
#print axioms RHBridge.R188PrincipalBandSerialization.coreMode_forces_smallPhysicalQuotient
#print axioms RHBridge.R188PrincipalBandSerialization.lowAndHighDeterminant_witness
#print axioms RHBridge.R188PrincipalBandSerialization.highShiftDeterminant_product
#print axioms RHBridge.R188PrincipalBandSerialization.reduciblePair_witness
#print axioms RHBridge.R188PrincipalBandSerialization.affineScalarAxis_residual
#print axioms RHBridge.R188PrincipalBandSerialization.affineCenter_needsTwoChannels
#print axioms RHBridge.R188PrincipalBandSerialization.completedFourChannel_square
#print axioms RHBridge.R188PrincipalBandSerialization.coherentPacket_crossLedger
#print axioms RHBridge.R188PrincipalBandSerialization.coherentCompleted_fixture
