"""Arb replay of one explicit Rayleigh vector for the Chuk local window.

The candidate vector is generated by the independent float scout, immediately
serialized to exact decimal rationals, and only then evaluated by Arb.  Thus
the reported ball is a rigorous value for a specific legal polynomial even
when the float eigensolver did not resolve the sign of the eigenvalue.

This certifies an upper witness for a finite clipped block.  A positive
Rayleigh value is not a lower bound for that block; a value below a proposed
floor rigorously falsifies that floor for the chosen clipping reduction.

Example:

    OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 PYTHONPATH=src \
      python3 src/chuk_scalar_arb_replay.py --cutoff 150 \
      --alpha-num 29 --alpha-den 100
"""

from __future__ import annotations

import argparse
import hashlib
import json
from math import prod
from time import time

import numpy as np
from flint import acb, arb, ctx, fmpq

import fullinf_unrestricted_n4_certificate as n4
from chuk_local_window_scout import A, clipped_block


def rational_decimal(text: str) -> fmpq:
    """Parse a scientific-notation decimal as an exact FLINT rational."""
    negative = text.startswith("-")
    text = text.lstrip("+-")
    if "e" in text.lower():
        mantissa, exponent_text = text.lower().split("e")
    else:
        mantissa, exponent_text = text, "0"
    if "." in mantissa:
        whole, fractional = mantissa.split(".")
    else:
        whole, fractional = mantissa, ""
    numerator = int((whole or "0") + fractional)
    denominator = 10 ** len(fractional)
    exponent = int(exponent_text)
    if exponent >= 0:
        numerator *= 10**exponent
    else:
        denominator *= 10 ** (-exponent)
    if negative:
        numerator = -numerator
    return fmpq(numerator, denominator)


def candidate(
    cutoff: int,
    alpha: float,
    degree_cutoff: int,
    nodes_per_panel: int,
) -> tuple[float, list[str]]:
    block = clipped_block(
        a=A,
        degree_cutoff=degree_cutoff,
        cutoff=cutoff,
        alpha=alpha,
        nodes_per_panel=nodes_per_panel,
        parity=0,
    )
    eigenvalues, eigenvectors = np.linalg.eigh(block)
    vector = eigenvectors[:, 0]
    if vector[np.argmax(np.abs(vector))] < 0:
        vector = -vector
    decimals = [format(float(value), ".17e") for value in vector]
    return float(eigenvalues[0]), decimals


def replay(
    *,
    cutoff: int,
    alpha_num: int,
    alpha_den: int,
    degree_cutoff: int = 80,
    nodes_per_panel: int = 96,
    precision: int = 192,
    tolerance_bits: int = 105,
    compute_band_mass: bool = False,
) -> dict:
    ctx.prec = precision
    ctx.threads = 1
    a = fmpq(4, 5)
    alpha_q = fmpq(alpha_num, alpha_den)
    alpha = arb(alpha_q)
    n4.A_HALF_WIDTH = a
    # The reusable n=4 driver precomputes this table only through its own
    # degree cutoff 132.  Scalar replays may deliberately probe a larger
    # Chuk head, so extend the exact integer table before the first-panel 0F1
    # evaluations.
    n4._ODD_DOUBLE_FACTORIAL = [
        prod(range(1, 2 * degree + 2, 2))
        for degree in range(degree_cutoff)
    ]

    float_eigenvalue, decimal_coefficients = candidate(
        cutoff, float(alpha_num / alpha_den), degree_cutoff, nodes_per_panel
    )
    coefficients = [rational_decimal(text) for text in decimal_coefficients]
    payload = json.dumps(decimal_coefficients, separators=(",", ":"))
    checksum = hashlib.sha256(payload.encode("ascii")).hexdigest()
    degrees = list(range(0, degree_cutoff, 2))
    norm_squared = sum((value * value for value in coefficients), fmpq(0))
    normalizers = [
        (2 * arb(a) * (2 * degree + 1)).sqrt() for degree in degrees
    ]
    phases = [(-1) ** (degree // 2) for degree in degrees]
    tolerance = arb(2) ** (-tolerance_bits)

    def fourier_value(r, left, analytic):
        value = acb(0)
        for coefficient, degree, normalizer, phase in zip(
            coefficients, degrees, normalizers, phases
        ):
            if left == 0:
                bessel = n4.spherical_j_series(degree, r)
            else:
                bessel = n4.spherical_j_panel(degree, r, analytic, left)
            value += arb(coefficient) * normalizer * phase * bessel
        return value

    weighted_integral = acb(0)
    band_integral = acb(0)
    started = time()
    for left in range(cutoff):
        def weighted(r, analytic, left=left):
            value = fourier_value(r, left, analytic)
            return (n4.omega(r) - alpha) * value * value

        panel = acb.integral(
            weighted,
            left,
            left + 1,
            abs_tol=tolerance,
            rel_tol=tolerance,
            deg_limit=80,
            eval_limit=100_000,
            depth_limit=25,
        )
        if not panel.is_finite():
            raise ArithmeticError(f"non-finite weighted panel {left}: {panel}")
        weighted_integral += panel

        if compute_band_mass:
            def unweighted(r, analytic, left=left):
                value = fourier_value(r, left, analytic)
                return value * value

            mass_panel = acb.integral(
                unweighted,
                left,
                left + 1,
                abs_tol=tolerance,
                rel_tol=tolerance,
                deg_limit=80,
                eval_limit=100_000,
                depth_limit=25,
            )
            if not mass_panel.is_finite():
                raise ArithmeticError(f"non-finite mass panel {left}: {mass_panel}")
            band_integral += mass_panel

    pole_value = acb(0)
    for coefficient, degree, normalizer in zip(
        coefficients, degrees, normalizers
    ):
        pole_value += (
            arb(coefficient)
            * normalizer
            * n4.spherical_i(degree, a / 2)
        )

    norm_ball = arb(norm_squared)
    quadratic_value = (
        alpha * norm_ball
        + weighted_integral.real / arb.pi()
        + 2 * (pole_value * pole_value).real
    )
    rayleigh = quadratic_value / norm_ball
    result = {
        "schema": "zeta23.chuk_scalar_arb_replay.v1",
        "evidence_label": "RIGOROUS_INTERVAL_COMPUTATION_FOR_ONE_RAYLEIGH_WITNESS",
        "physical_half_width": "4/5",
        "L_program": "16/5",
        "cutoff": cutoff,
        "alpha": f"{alpha_num}/{alpha_den}",
        "degree_cutoff": degree_cutoff,
        "even_degrees": degrees,
        "candidate_nodes_per_panel": nodes_per_panel,
        "candidate_float_eigenvalue": float_eigenvalue,
        "coefficient_decimal_strings": decimal_coefficients,
        "coefficient_sha256": checksum,
        "precision_bits": precision,
        "integration_tolerance_bits": tolerance_bits,
        "norm_squared_ball": norm_ball.str(40, radius=True),
        "weighted_integral_ball": weighted_integral.real.str(40, radius=True),
        "weighted_integral_imaginary_ball": weighted_integral.imag.str(15, radius=True),
        "pole_ball": (2 * (pole_value * pole_value).real).str(40, radius=True),
        "rayleigh_ball": rayleigh.str(50, radius=True),
        "rayleigh_positive": bool(rayleigh > arb(0)),
        "rayleigh_below_8p9e_minus_18": bool(
            rayleigh < arb(fmpq(89, 10**19))
        ),
        "elapsed_seconds": time() - started,
        "scope_warning": (
            "This is an exact-polynomial upper witness, not a lower bound "
            "for the finite block or the full localized form."
        ),
    }
    if compute_band_mass:
        normalized_band_mass = band_integral.real / (arb.pi() * norm_ball)
        result["normalized_band_mass_ball"] = normalized_band_mass.str(
            50, radius=True
        )
        result["normalized_outside_mass_ball"] = (
            1 - normalized_band_mass
        ).str(50, radius=True)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cutoff", required=True, type=int)
    parser.add_argument("--alpha-num", required=True, type=int)
    parser.add_argument("--alpha-den", required=True, type=int)
    parser.add_argument("--degree-cutoff", type=int, default=80)
    parser.add_argument("--nodes-per-panel", type=int, default=96)
    parser.add_argument("--precision", type=int, default=192)
    parser.add_argument("--tolerance-bits", type=int, default=105)
    parser.add_argument("--band-mass", action="store_true")
    args = parser.parse_args()
    print(
        json.dumps(
            replay(
                cutoff=args.cutoff,
                alpha_num=args.alpha_num,
                alpha_den=args.alpha_den,
                degree_cutoff=args.degree_cutoff,
                nodes_per_panel=args.nodes_per_panel,
                precision=args.precision,
                tolerance_bits=args.tolerance_bits,
                compute_band_mass=args.band_mass,
            ),
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
