"""Exact dual geometry of the fixed-sum reciprocal curve.

For

    gamma(t) = (t, lambda/t, lambda/(1-t)),
    Phi(t) = (-m,h,k) dot gamma(t),

this module records the rational tangent direction, the full lattice of
integer stationary frequencies, its primitive cubic-caustic ray, and the
affine character which decides whether the tangent line itself meets the
integer lattice.  These identities classify exact major arcs; they do not
prove cancellation between different tangent locations.
"""

from __future__ import annotations

import cmath
from dataclasses import dataclass
from fractions import Fraction
from math import gcd
from typing import Mapping


Frequency = tuple[int, int, int]  # coordinates (-m,h,k)
Vector = tuple[int, int, int]


def _extended_gcd(a: int, b: int) -> tuple[int, int, int]:
    if b == 0:
        return a, 1, 0
    common, x, y = _extended_gcd(b, a % b)
    return common, y, x - (a // b) * y


def _dot(left: tuple[int | Fraction, ...], right: tuple[int | Fraction, ...]) -> Fraction:
    return sum((Fraction(x) * Fraction(y) for x, y in zip(left, right)), Fraction())


@dataclass(frozen=True)
class RationalTangentData:
    """Primitive tangent and normal-lattice data at ``t=r/(r+s)``.

    ``lambda_numerator/lambda_denominator`` and ``r/s`` must both be in
    lowest terms.  Frequencies use coordinates ``xi=(-m,h,k)``.
    """

    lambda_numerator: int
    lambda_denominator: int
    r: int
    s: int
    primitive_direction: Vector
    stationary_basis: tuple[Frequency, Frequency]
    primitive_caustic: Frequency


@dataclass(frozen=True)
class SymmetricTangentAliasData:
    """Exact stationary alias data for ``lambda=1/4``."""

    r: int
    s: int
    direction: Vector
    parity_index: int


def rational_tangent_data(
    lambda_numerator: int,
    lambda_denominator: int,
    r: int,
    s: int,
) -> RationalTangentData:
    """Return the exact primitive tangent and stationary frequency lattices.

    Put ``P=lambda_numerator``, ``Q=lambda_denominator``, and ``n=r+s``.
    A primitive integer vector parallel to ``gamma'(r/n)`` is obtained by
    dividing

        (Q*r^2*s^2, -P*n^2*s^2, P*n^2*r^2)

    by ``gcd(P*n^2,Q*r^2*s^2)``.  The complete saturated normal lattice is
    generated by the two returned stationary frequencies.  Its primitive
    binormal (the cubic caustic) is

        (P*n^3/c, (Q/c)*r^3, -(Q/c)*s^3),
        c=gcd(Q,n^3).
    """

    P, Q = lambda_numerator, lambda_denominator
    if min(P, Q, r, s) <= 0:
        raise ValueError("all parameters must be positive")
    if gcd(P, Q) != 1 or gcd(r, s) != 1:
        raise ValueError("lambda and r/s must be reduced")

    n = r + s
    common = gcd(P * n * n, Q * r * r * s * s)
    raw_direction = (
        Q * r * r * s * s,
        -P * n * n * s * s,
        P * n * n * r * r,
    )
    direction = tuple(value // common for value in raw_direction)
    assert gcd(gcd(abs(direction[0]), abs(direction[1])), abs(direction[2])) == 1

    bezout_gcd, u, plus_v = _extended_gcd(r * r, s * s)
    assert bezout_gcd == 1
    v = -plus_v
    assert u * r * r - v * s * s == 1

    A_reduced = P * n * n // common
    B_reduced = Q * r * r * s * s // common
    zero_dual = (0, r * r, s * s)
    transverse = (-A_reduced, B_reduced * v, B_reduced * u)
    assert _dot(direction, zero_dual) == 0
    assert _dot(direction, transverse) == 0

    caustic_common = gcd(Q, n**3)
    caustic = (
        P * n**3 // caustic_common,
        Q * r**3 // caustic_common,
        -Q * s**3 // caustic_common,
    )
    assert gcd(gcd(abs(caustic[0]), abs(caustic[1])), abs(caustic[2])) == 1
    assert _dot(direction, caustic) == 0

    return RationalTangentData(
        lambda_numerator=P,
        lambda_denominator=Q,
        r=r,
        s=s,
        primitive_direction=direction,  # type: ignore[arg-type]
        stationary_basis=(zero_dual, transverse),
        primitive_caustic=caustic,
    )


def normalized_phase_derivatives(
    lambda_value: Fraction,
    h: int,
    k: int,
    m: int,
    t: Fraction,
) -> dict[str, Fraction]:
    """Return the first four derivatives of the normalized phase."""

    if lambda_value <= 0 or t <= 0 or t >= 1:
        raise ValueError("require lambda>0 and 0<t<1")
    one_minus = 1 - t
    return {
        "first": -lambda_value * h / t**2
        + lambda_value * k / one_minus**2
        - m,
        "second": 2 * lambda_value * h / t**3
        + 2 * lambda_value * k / one_minus**3,
        "third": -6 * lambda_value * h / t**4
        + 6 * lambda_value * k / one_minus**4,
        "fourth": 24 * lambda_value * h / t**5
        + 24 * lambda_value * k / one_minus**5,
    }


def stationary_quartic_value(
    lambda_value: Fraction,
    h: int,
    k: int,
    m: int,
    t: Fraction,
) -> Fraction:
    """Return the cleared stationary polynomial.

    It is ``-t^2(1-t)^2 Phi'(t)`` and therefore has the same interior roots
    as the stationary equation.
    """

    one_minus = 1 - t
    return (
        m * t**2 * one_minus**2
        + lambda_value * h * one_minus**2
        - lambda_value * k * t**2
    )


def interior_caustic_discriminant(
    lambda_value: Fraction, h: int, k: int, m: int
) -> Fraction:
    """Return the non-endpoint factor in the stationary quartic discriminant.

    The full quartic discriminant is

        -16*lambda^2*h*k*m * interior_caustic_discriminant(...).

    For ``h*k<0`` with the physical sign of ``m``, its vanishing is
    equivalent to a double stationary point in ``0<t<1``.
    """

    return (m + lambda_value * (h - k)) ** 3 + 27 * lambda_value**2 * h * k * m


def physical_tangent_point(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
) -> tuple[Fraction, Fraction, Fraction]:
    """Return ``S*gamma(r/(r+s))`` in physical ``(a,v,w)`` coordinates."""

    if min(lambda_numerator, lambda_denominator, S, r, s) <= 0:
        raise ValueError("all parameters must be positive")
    if gcd(lambda_numerator, lambda_denominator) != 1 or gcd(r, s) != 1:
        raise ValueError("lambda and r/s must be reduced")
    n = r + s
    return (
        Fraction(S * r, n),
        Fraction(lambda_numerator * S * n, lambda_denominator * r),
        Fraction(lambda_numerator * S * n, lambda_denominator * s),
    )


def stationary_affine_heights(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
) -> tuple[Fraction, Fraction]:
    """Evaluate a saturated stationary basis at the tangent point.

    The rational tangent line meets ``Z^3`` exactly when both returned
    heights are integers.  This is the affine condition missing from the
    mere rationality of its tangent direction.
    """

    data = rational_tangent_data(lambda_numerator, lambda_denominator, r, s)
    point = physical_tangent_point(lambda_numerator, lambda_denominator, S, r, s)
    return tuple(_dot(frequency, point) for frequency in data.stationary_basis)  # type: ignore[return-value]


def tangent_line_meets_integer_lattice(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
) -> bool:
    """Decide exactly whether the rational tangent line intersects ``Z^3``."""

    heights = stationary_affine_heights(
        lambda_numerator, lambda_denominator, S, r, s
    )
    return all(height.denominator == 1 for height in heights)


def caustic_phase_height(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
) -> Fraction:
    """Return the phase at the primitive cubic stationary point.

    If ``c=gcd(Q,(r+s)^3)``, this equals

        P*S*(r+s)^2*(2*r-s)/c.

    Its integrality alone does not imply that the tangent line meets the
    integer lattice; both generators in ``stationary_affine_heights`` are
    needed.
    """

    data = rational_tangent_data(lambda_numerator, lambda_denominator, r, s)
    point = physical_tangent_point(lambda_numerator, lambda_denominator, S, r, s)
    return _dot(data.primitive_caustic, point)


def tangent_line_intercepts(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
) -> tuple[Fraction, Fraction, Vector]:
    """Return ``(alpha,beta,V)`` for the tangent-line intercept form.

    If ``V=(R,-P_0,K_0)`` is the primitive tangent direction, then the line
    can be written

        (a, alpha-(P_0/R)*a, beta+(K_0/R)*a).
    """

    data = rational_tangent_data(lambda_numerator, lambda_denominator, r, s)
    a_0, v_0, w_0 = physical_tangent_point(
        lambda_numerator, lambda_denominator, S, r, s
    )
    R, minus_left_step, right_step = data.primitive_direction
    left_step = -minus_left_step
    alpha = v_0 + Fraction(left_step, R) * a_0
    beta = w_0 - Fraction(right_step, R) * a_0
    return alpha, beta, data.primitive_direction


def stationary_coefficient_mass(
    coefficients: Mapping[int, complex],
    direction: Vector,
    alpha: Fraction | float,
    beta: Fraction | float,
) -> complex:
    """Sum ``c_h c_k e(h alpha+k beta)`` over exact stationary modes.

    For ``direction=(R,-P_0,K_0)``, stationarity with an integer Poisson
    frequency is equivalent to ``k*K_0-h*P_0 == 0 (mod R)``.
    """

    R, minus_left_step, right_step = direction
    left_step = -minus_left_step
    if R <= 0 or left_step <= 0 or right_step <= 0:
        raise ValueError("direction must have signs (positive,negative,positive)")
    if gcd(gcd(R, left_step), right_step) != 1:
        raise ValueError("direction must be primitive")
    total = 0j
    for h, left in coefficients.items():
        for k, right in coefficients.items():
            if (k * right_step - h * left_step) % R == 0:
                total += (
                    complex(left)
                    * complex(right)
                    * cmath.exp(2j * cmath.pi * (h * float(alpha) + k * float(beta)))
                )
    return total


def cyclic_tangent_mask_average(
    coefficients: Mapping[int, complex],
    direction: Vector,
    alpha: Fraction | float,
    beta: Fraction | float,
) -> complex:
    """Regroup the exact stationary mass as a cyclic tangent-mask average.

    If ``P_c(theta)=sum_h c_h e(h theta)``, the returned value is

        (1/R) sum_(j mod R)
          P_c(alpha-j*P_0/R) P_c(beta+j*K_0/R).

    The congruence detector makes this exactly equal to
    ``stationary_coefficient_mass``.  No stationary-phase amplitude is
    included in either side.
    """

    R, minus_left_step, right_step = direction
    left_step = -minus_left_step
    if R <= 0 or left_step <= 0 or right_step <= 0:
        raise ValueError("direction must have signs (positive,negative,positive)")
    if gcd(gcd(R, left_step), right_step) != 1:
        raise ValueError("direction must be primitive")

    def polynomial(theta: float) -> complex:
        return sum(
            complex(value) * cmath.exp(2j * cmath.pi * frequency * theta)
            for frequency, value in coefficients.items()
        )

    return sum(
        polynomial(float(alpha) - j * left_step / R)
        * polynomial(float(beta) + j * right_step / R)
        for j in range(R)
    ) / R


def tangent_orbit_has_integer_point(
    direction: Vector, alpha: Fraction, beta: Fraction
) -> bool:
    """Check whether one residue point in the cyclic tangent orbit is integral."""

    R, minus_left_step, right_step = direction
    left_step = -minus_left_step
    if R <= 0 or left_step <= 0 or right_step <= 0:
        raise ValueError("direction must have signs (positive,negative,positive)")
    for j in range(R):
        left = alpha - Fraction(j * left_step, R)
        right = beta + Fraction(j * right_step, R)
        if left.denominator == right.denominator == 1:
            return True
    return False


def _distance_to_integer(value: Fraction) -> Fraction:
    remainder = value.numerator % value.denominator
    return Fraction(min(remainder, value.denominator - remainder), value.denominator)


def tangent_orbit_linf_distance(
    direction: Vector, alpha: Fraction, beta: Fraction
) -> Fraction:
    """Return the exact closest cyclic-orbit distance to ``Z^2``.

    This is

        min_(j mod R) max(||alpha-j*P_0/R||,||beta+j*K_0/R||).

    It vanishes exactly when the affine tangent line meets ``Z^3``.
    """

    R, minus_left_step, right_step = direction
    left_step = -minus_left_step
    if R <= 0 or left_step <= 0 or right_step <= 0:
        raise ValueError("direction must have signs (positive,negative,positive)")
    if gcd(gcd(R, left_step), right_step) != 1:
        raise ValueError("direction must be primitive")
    return min(
        max(
            _distance_to_integer(alpha - Fraction(j * left_step, R)),
            _distance_to_integer(beta + Fraction(j * right_step, R)),
        )
        for j in range(R)
    )


def normalized_fejer_orbit_eta_bound(order: int, eta: Fraction) -> Fraction:
    """Return the sharp elementary envelope from cyclic orbit distance.

    For the height-one normalized Fejer polynomial

        P_N(theta)=N^(-2)|sum_(0<=j<N)e(j theta)|^2,

    its cyclic two-mask average is at most the returned quantity.  The proof
    uses ``P_N<=1`` and, for ``||theta||>0``,

        P_N(theta)<=1/(4*N^2*||theta||^2).
    """

    if order <= 0 or eta < 0 or eta > Fraction(1, 2):
        raise ValueError("require order>0 and 0<=eta<=1/2")
    if eta == 0:
        return Fraction(1)
    return min(Fraction(1), Fraction(1, 4 * order * order) / eta**2)


def symmetric_tangent_alias_data(r: int, s: int) -> SymmetricTangentAliasData:
    """Return the exact ``lambda=1/4`` tangent direction and parity index.

    For coprime ``r,s`` and ``n=r+s`` the primitive direction is

        (4*r^2*s^2/g, -n^2*s^2/g, n^2*r^2/g),
        g=gcd(n^2,4).

    If ``n`` is even, then ``r,s`` are both odd, ``g=4``, and the stationary
    aliases are independent.  If ``n`` is odd, one of ``r,s`` is even,
    ``g=1``, and an additional index-four congruence remains.
    """

    if min(r, s) <= 0 or gcd(r, s) != 1:
        raise ValueError("r/s must be positive and reduced")
    n = r + s
    parity_index = 1 if n % 2 == 0 else 4
    common = 4 // parity_index
    direction = (
        4 * r * r * s * s // common,
        -(n * n * s * s // common),
        n * n * r * r // common,
    )
    reference = rational_tangent_data(1, 4, r, s).primitive_direction
    assert direction == reference
    return SymmetricTangentAliasData(
        r=r,
        s=s,
        direction=direction,
        parity_index=parity_index,
    )


def symmetric_stationary_alias(
    h: int, k: int, r: int, s: int
) -> tuple[bool, int, int, int]:
    """Recognize exact stationary aliases in the symmetric chart.

    The return value is ``(is_alias,a,b,m)``.  Every alias has

        h=r^2*a,       k=s^2*b,
        m=(r+s)^2*(b-a)/4.

    When ``r+s`` is odd, integrality requires ``b-a==0 (mod 4)``.  When it
    is even, the condition is automatic.
    """

    data = symmetric_tangent_alias_data(r, s)
    if h % (r * r) != 0 or k % (s * s) != 0:
        return False, 0, 0, 0
    a, b = h // (r * r), k // (s * s)
    if (b - a) % data.parity_index != 0:
        return False, 0, 0, 0
    m = (r + s) ** 2 * (b - a) // 4
    R, minus_left_step, right_step = data.direction
    assert m * R == k * right_step + h * minus_left_step
    return True, a, b, m


def normalized_fejer_grid_maximum(order: int, modulus: int) -> Fraction:
    """Return the exact maximum of a normalized Fejer grid average.

    If ``P_N`` is the height-one normalized Fejer polynomial, then

        max_theta (1/M) sum_(u mod M) P_N(theta+u/M)

    equals the returned value.  Writing ``N=qM+r``, it is

        [r(q+1)^2+(M-r)q^2]/N^2.

    This follows by sorting ``0,...,N-1`` into residue classes modulo ``M``;
    the maximum occurs when all phases in each class align.
    """

    if order <= 0 or modulus <= 0:
        raise ValueError("order and modulus must be positive")
    quotient, remainder = divmod(order, modulus)
    numerator = (
        remainder * (quotient + 1) ** 2
        + (modulus - remainder) * quotient**2
    )
    return Fraction(numerator, order * order)


def symmetric_cyclic_fejer_bound(order: int, r: int, s: int) -> Fraction:
    """Return the sharp product-grid ceiling for one symmetric tangent orbit.

    The cyclic orbit is a direct product of the ``r^2`` and ``s^2`` grids
    when ``r+s`` is even.  When ``r+s`` is odd it is an average of four such
    product grids.  In both cases its two-mask average is at most

        B_N(r^2)*B_N(s^2),

    where ``B_N`` is ``normalized_fejer_grid_maximum``.
    """

    symmetric_tangent_alias_data(r, s)
    return normalized_fejer_grid_maximum(
        order, r * r
    ) * normalized_fejer_grid_maximum(order, s * s)


def _fejer_alias_residue_masses(
    order: int, modulus: int, residue_modulus: int
) -> tuple[Fraction, ...]:
    masses = [Fraction() for _ in range(residue_modulus)]
    largest_alias = (order - 1) // modulus
    for alias in range(-largest_alias, largest_alias + 1):
        coefficient = Fraction(order - abs(modulus * alias), order * order)
        masses[alias % residue_modulus] += coefficient
    return tuple(masses)


def symmetric_cyclic_fejer_maximum(order: int, r: int, s: int) -> Fraction:
    """Return the exact intercept-uniform maximum of the symmetric orbit.

    In the independent parity case this is ``B_N(r^2)B_N(s^2)``.  In the
    index-four case, let ``C_(M,c)`` be the total triangular coefficient on
    aliases ``a==c (mod 4)`` with frequency ``M*a``.  The exact maximum is

        sum_(c mod 4) C_(r^2,c) C_(s^2,c).

    All Fourier coefficients are nonnegative, so the maximum is attained at
    zero intercepts.
    """

    if order <= 0:
        raise ValueError("order must be positive")
    data = symmetric_tangent_alias_data(r, s)
    residue_modulus = data.parity_index
    left = _fejer_alias_residue_masses(order, r * r, residue_modulus)
    right = _fejer_alias_residue_masses(order, s * s, residue_modulus)
    maximum = sum((x * y for x, y in zip(left, right)), Fraction())
    assert maximum <= symmetric_cyclic_fejer_bound(order, r, s)
    return maximum


def remote_symmetric_orbit_exponent_ledger() -> dict[str, Fraction]:
    """Return the critical powers in the high primitive-denominator branch.

    At the worst compact-core endpoint, the primal reduction gives
    ``p>=D^(13/48)``.  In a compact collar ``r,s`` are both comparable to
    ``p``, so the symmetric cyclic mass is ``O(p^(-4))`` until the still
    stronger ``H^(-2)`` plateau is reached.  Since ``H=D^(17/16)``, this is

        p^(-4) <= D^(-13/12) = H^(-1) D^(-1/48).
    """

    primitive_floor = Fraction(13, 48)
    H = Fraction(17, 16)
    fourth_power = 4 * primitive_floor
    return {
        "primitive_p_floor": primitive_floor,
        "H": H,
        "p_fourth_power_floor": fourth_power,
        "excess_over_H": fourth_power - H,
        "cyclic_mass_ceiling": -fourth_power,
    }


def exact_remote_stationary_sector_exponent_ledger() -> dict[str, Fraction]:
    """Ledger for summing every exact rational remote stationary direction.

    A dyadic family ``p~P`` has ``O(P^2)`` primitive directions and each has
    coefficient mass ``O(P^-4)``.  The opposite-sign uniform Airy ledger is
    ``D^(49/48)`` before this direction saving.  At
    ``P>=D^(13/48)`` the exact rational-stationary sector is therefore at
    most ``D^(23/48)``, a factor ``D^(-1/48)`` below the square-root target.
    """

    Airy = Fraction(49, 48)
    primitive_floor = Fraction(13, 48)
    direction_saving = 2 * primitive_floor
    result = Airy - direction_saving
    target = Fraction(1, 2)
    return {
        "Airy_before_direction_sum": Airy,
        "primitive_p_floor": primitive_floor,
        "direction_sum_saving": direction_saving,
        "exact_remote_sector": result,
        "target": target,
        "slack_below_target": target - result,
    }


def tangent_line_point_and_product_errors(
    lambda_numerator: int,
    lambda_denominator: int,
    S: int,
    r: int,
    s: int,
    a: Fraction,
) -> tuple[tuple[Fraction, Fraction, Fraction], tuple[Fraction, Fraction]]:
    """Evaluate the tangent line and its exact two quadratic product errors."""

    P, Q = lambda_numerator, lambda_denominator
    if min(P, Q, S, r, s) <= 0 or gcd(P, Q) != 1 or gcd(r, s) != 1:
        raise ValueError("positive reduced parameters are required")
    n = r + s
    center = Fraction(S * r, n)
    complement = Fraction(S * s, n)
    C = Fraction(P * S * S, Q)
    offset = a - center
    v = C / center - C * offset / center**2
    w = C / complement + C * offset / complement**2
    first_error = a * v - C
    second_error = (S - a) * w - C
    assert first_error == -C * offset**2 / center**2
    assert second_error == -C * offset**2 / complement**2
    return (a, v, w), (first_error, second_error)


def special_center_reduced_lambda(q: int, x: int, S: int) -> Fraction:
    """Return the exact physical ratio ``(q^3/(8x))/S^2`` in lowest terms."""

    if min(q, x, S) <= 0:
        raise ValueError("q,x,S must be positive")
    return Fraction(q**3, 8 * x * S * S)


def caustic_frequency_size_gate(
    lambda_denominator: int, r: int, s: int
) -> tuple[int, int]:
    """Return the primitive cube multiplier and its largest Fejer frequency.

    The primitive caustic has ``d=Q/gcd(Q,(r+s)^3)`` and
    ``max(|h|,|k|)=d*max(r,s)^3``.  In particular, existence inside a box
    ``|h|,|k|<=H`` forces ``Q<=8H``.
    """

    if min(lambda_denominator, r, s) <= 0 or gcd(r, s) != 1:
        raise ValueError("positive Q and reduced r/s are required")
    n = r + s
    multiplier = lambda_denominator // gcd(lambda_denominator, n**3)
    return multiplier, multiplier * max(r, s) ** 3


def symmetric_primal_cusp_coordinates(Q: int, y: int) -> dict[str, Fraction]:
    """Match the primal carrier cusp to the centered dual coordinates.

    On the exact curve ``C=Q^2,S=2Q`` put

        A=Q*y^2/(Q^2-y^2),  t=y^3/(Q^2-y^2).

    The carrier deviations from the swapped tangent are
    ``rho=2A`` and ``kappa=2t`` and obey

        rho^3 = kappa^2*(rho+2Q).
    """

    if Q <= 0 or abs(y) >= Q:
        raise ValueError("require Q>0 and |y|<Q")
    denominator = Q * Q - y * y
    A = Fraction(Q * y * y, denominator)
    t = Fraction(y**3, denominator)
    rho, kappa = 2 * A, 2 * t
    assert rho**3 == kappa**2 * (rho + 2 * Q)
    return {"A": A, "t": t, "rho": rho, "kappa": kappa}


def symmetric_error_cusp_identity(
    Q: int, y: int, left_shift: int, right_shift: int
) -> dict[str, int]:
    """Return the exact error-deformed primal cusp identity.

    Write

        v=Q-y+left_shift,       w=Q+y+right_shift,
        e=(Q+y)*v-Q^2,          f=(Q-y)*w-Q^2,
        rho=left_shift+right_shift,
        kappa=right_shift-left_shift,
        sigma=e+f,              tau=e-f.

    Then ``tau=y*rho-Q*kappa`` and

        Q*(rho^3-kappa^2*(rho+2Q))
          =sigma*rho^2+tau*kappa*(rho+4Q)+2*tau^2.

    The identity is a primal equation for the same cusp whose Fourier-dual
    coordinates are recorded by ``symmetric_primal_cusp_coordinates``.
    """

    if Q <= 0 or abs(y) >= Q:
        raise ValueError("require Q>0 and |y|<Q")
    e = left_shift * (Q + y) - y * y
    f = right_shift * (Q - y) - y * y
    rho = left_shift + right_shift
    kappa = right_shift - left_shift
    sigma, tau = e + f, e - f
    left = Q * (rho**3 - kappa**2 * (rho + 2 * Q))
    right = sigma * rho**2 + tau * kappa * (rho + 4 * Q) + 2 * tau**2
    assert tau == y * rho - Q * kappa
    assert left == right
    return {
        "e": e,
        "f": f,
        "rho": rho,
        "kappa": kappa,
        "sigma": sigma,
        "tau": tau,
        "left": left,
        "right": right,
    }
