"""High-primitive support gates for the QP phase-jet strategy.

This module records two exact facts.

First, the primitive phase which is both stationary and curvature-free at a
rational tangent has frequency size at least ``p^3``.  Consequently no
bounded integer combination of physical frequencies of size at most ``H``
can synthesize that cubic character: the coefficient (or tensor-degree)
cost is at least ``p^3/(2H)``, and hence ``>>p^3/H`` at power scale.

Second, recovery of the full quadratic/cubic residual fingerprint is more
than the cluster count needs.  If a physical quotient-jet theorem recovers
only the primitive direction ``(p,d)`` (up to reflection), then the product
bands contain ``O(1+B/p)`` points over that direction.  At the worst QP
endpoint this is ``D^(329/480+o(1))``, below both relevant phase-jet cluster
ceilings.

Neither fact proves the missing physical packet-to-direction transference.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import floor, gcd
from typing import Iterable, Sequence


Frequency = tuple[int, int, int]  # coordinates (-m,h,k)


def primitive_cubic_frequency(p: int, d: int) -> Frequency:
    """Return the primitive integral cubic normal at ``t=(p+d)/(2p)``.

    Put ``chi=gcd(p+d,p-d)``, ``a=(p+d)/chi``, ``b=(p-d)/chi`` and
    ``N=a+b``.  For

    ``phi(t)=(-m)*t+h/(4t)+k/(4(1-t))``

    the simultaneous equations ``phi'(a/N)=phi''(a/N)=0`` have integral
    solution lattice generated by

    ``(N^3/c0,4a^3/c0,-4b^3/c0)``, ``c0=gcd(4,N^3)``.
    """

    if p <= abs(d) or gcd(p, abs(d)) != 1:
        raise ValueError("require p>|d| and gcd(p,d)=1")
    parity = gcd(p + d, p - d)
    if parity not in (1, 2):
        raise AssertionError("a primitive direction has parity one or two")
    a, b = (p + d) // parity, (p - d) // parity
    N = a + b
    c0 = gcd(4, N**3)
    frequency = (N**3 // c0, 4 * a**3 // c0, -4 * b**3 // c0)
    if gcd(gcd(abs(frequency[0]), abs(frequency[1])), abs(frequency[2])) != 1:
        raise AssertionError("the cubic normal should be primitive")
    return frequency


def phase_first_second_at_tangent(
    frequency: Frequency, p: int, d: int
) -> tuple[Fraction, Fraction]:
    """Evaluate the first two normalized phase derivatives exactly."""

    if p <= abs(d) or gcd(p, abs(d)) != 1:
        raise ValueError("require p>|d| and gcd(p,d)=1")
    minus_m, h, k = frequency
    t = Fraction(p + d, 2 * p)
    first = (
        Fraction(minus_m)
        - Fraction(h, 4) / t**2
        + Fraction(k, 4) / (1 - t) ** 2
    )
    second = Fraction(h, 2) / t**3 + Fraction(k, 2) / (1 - t) ** 3
    return first, second


def cubic_ray_multiplier(
    frequency: Frequency, p: int, d: int
) -> int | None:
    """Return ``q`` when ``frequency=q*primitive_cubic_frequency``.

    The return value is ``None`` off the cubic ray.  In particular this
    gives a finite exact checker for the two derivative equations.
    """

    generator = primitive_cubic_frequency(p, d)
    multiplier: int | None = None
    for value, primitive in zip(frequency, generator):
        if primitive == 0:
            if value != 0:
                return None
            continue
        if value % primitive:
            return None
        candidate = value // primitive
        if multiplier is None:
            multiplier = candidate
        elif multiplier != candidate:
            return None
    return multiplier if multiplier is not None else 0


@dataclass(frozen=True)
class CubicSynthesisAudit:
    aggregate_frequency: Frequency
    cubic_multiplier: int
    coefficient_mass: int
    support_bound: int
    primitive_size: int
    primitive_fejer_size: int
    forced_mass_lower_bound: Fraction


def audit_supported_cubic_synthesis(
    frequencies: Sequence[Frequency],
    coefficients: Sequence[int],
    p: int,
    d: int,
    support_bound: int,
) -> CubicSynthesisAudit:
    """Audit an integer synthesis of a nonzero cubic normal.

    The two Fejer coordinates ``(h,k)`` of every supplied mode must lie in
    the box of radius ``H``; no separate cutoff on the Poisson coordinate is
    needed for this audit.
    If their integer combination lies on the nonzero cubic ray, the triangle
    inequality proves

    ``sum |c_j| >= max(|h_3|,|k_3|)/H >= p^3/(2H)``.

    In a fixed interior collar the last lower bound is ``>>p^3/H``.
    """

    if support_bound <= 0 or len(frequencies) != len(coefficients):
        raise ValueError("require H>0 and equally long mode/coefficient lists")
    if not frequencies:
        raise ValueError("at least one supported mode is required")
    for frequency in frequencies:
        if max(abs(frequency[1]), abs(frequency[2])) > support_bound:
            raise ValueError("a supplied Fejer mode exceeds the support bound")
    aggregate = tuple(
        sum(coefficient * frequency[index]
            for frequency, coefficient in zip(frequencies, coefficients))
        for index in range(3)
    )
    multiplier = cubic_ray_multiplier(aggregate, p, d)
    if multiplier in (None, 0):
        raise ValueError("the aggregate is not a nonzero cubic normal")
    primitive = primitive_cubic_frequency(p, d)
    primitive_size = max(map(abs, primitive))
    primitive_fejer_size = max(abs(primitive[1]), abs(primitive[2]))
    if 2 * primitive_fejer_size < p**3:
        raise AssertionError("the primitive cubic Fejer size is too small")
    mass = sum(abs(value) for value in coefficients)
    lower = Fraction(abs(multiplier) * primitive_fejer_size, support_bound)
    if mass < lower:
        raise AssertionError("triangle-inequality support lower bound failed")
    return CubicSynthesisAudit(
        aggregate_frequency=aggregate,
        cubic_multiplier=multiplier,
        coefficient_mass=mass,
        support_bound=support_bound,
        primitive_size=primitive_size,
        primitive_fejer_size=primitive_fejer_size,
        forced_mass_lower_bound=lower,
    )


def direction_fiber_point_bound(B: int, p: int, content_floor: int = 1) -> int:
    """Bound points over one oriented primitive direction in a dyadic content cell.

    Suppose ``|e|<=A<=B``, ``g>=content_floor`` and
    ``e-f=g*n`` with ``n=p*y-Q*d``.  Then ``|n|<=2B/g``.  As integral ``y``
    varies at fixed ``(Q,p,d)``, the values of ``n`` are spaced by ``p``.
    Hence there are at most

    ``1+floor(4B/(content_floor*p))``

    possible carriers.  In the QP application, the narrow-band content
    spacing lemma gives at most one admissible ``g`` per carrier ``y``.
    """

    if min(B, p, content_floor) <= 0:
        raise ValueError("require B,p,G>0")
    return 1 + floor(Fraction(4 * B, content_floor * p))


def count_reduced_differences_in_direction(
    Q: int,
    p: int,
    d: int,
    B: int,
    content_floor: int = 1,
) -> tuple[int, ...]:
    """Enumerate the possible ``n=p*y-Q*d`` in the elementary direction bound."""

    if Q <= 0 or p <= abs(d) or gcd(p, abs(d)) != 1:
        raise ValueError("invalid primitive direction")
    if B <= 0 or content_floor <= 0:
        raise ValueError("require B,G>0")
    radius = Fraction(2 * B, content_floor)
    # A deliberately simple finite interval containing every admissible y.
    y_center = Fraction(Q * d, p)
    lower = floor(y_center - radius / p) - 1
    upper = floor(y_center + radius / p) + 2
    values = tuple(
        p * y - Q * d
        for y in range(lower, upper + 1)
        if abs(p * y - Q * d) <= radius
    )
    if len(values) > direction_fiber_point_bound(B, p, content_floor):
        raise AssertionError("the arithmetic progression bound failed")
    return values


def content_unique_in_compact_narrow_band(
    Q: int, y: int, p: int, d: int, A: int
) -> bool:
    """Return the exact sufficient spacing condition for unique content.

    Changing ``g`` by one changes the left error by
    ``(p-d)(Q+y)/2`` (up to reflection).  The orientation-free sufficient
    condition used here is

    ``(p-|d|)(Q-|y|)>4A``.
    """

    if Q <= abs(y) or p <= abs(d) or A < 0:
        raise ValueError("invalid compact-band parameters")
    return (p - abs(d)) * (Q - abs(y)) > 4 * A


def high_p_transference_exponent_ledger() -> dict[str, Fraction]:
    """Return the exact endpoint powers for the no-go and direction alternative."""

    Q = Fraction(33, 16)
    H = Fraction(17, 16)
    B = Fraction(7, 6)
    p_floor = Fraction(77, 160)
    cubic_cost = 3 * p_floor - H
    direction_fiber = B - p_floor
    full_eta = Fraction(1, 6)
    closing_eta = Fraction(7, 48)
    full_cluster = B - full_eta
    closing_cluster = B - closing_eta
    assert cubic_cost == Fraction(61, 160)
    assert direction_fiber == Fraction(329, 480)
    assert full_cluster == 1
    assert closing_cluster == Fraction(49, 48)
    return {
        "Q": Q,
        "H": H,
        "B": B,
        "residual_p_floor": p_floor,
        "bounded_probe_cubic_cost": cubic_cost,
        "direction_fiber": direction_fiber,
        "full_eta": full_eta,
        "full_cluster_ceiling": full_cluster,
        "full_direction_margin": full_cluster - direction_fiber,
        "closing_eta": closing_eta,
        "closing_cluster_ceiling": closing_cluster,
        "closing_direction_margin": closing_cluster - direction_fiber,
    }
